site_name: Ahmad Ahmad Discord Server Notiz an Staffteam
site_description: Anfrage an Ahmad.neu sein Serverteam umzuÃ¤ndern.
site_author: karma.meme
repo_url: https://github.com/h-ntai/schlussstrich/
repo_name: GitHub
edit_uri: blob/main/docs/
copyright: Copyright Â© Karma (karma.meme) 2022
site_dir: build/
docs_dir: docs/
theme: 
  name: material
  custom_dir: docs/overrides
  logo: guilded.svg
  favicon: logo.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
extra_css: [extra.css]
dev_addr: 127.0.0.1:80
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: ðŸ”—
      toc_depth: 3
